--[[
-- HELPERS
]]

local M = {}

-- function map
-- mode : n -> Normal, i -> Insert
-- lhs  : custom keybinds
-- rhs  : existing keybinds or commands
-- ops  : additionals options. see :h map-arguments
function M.map(mode, lhs, rhs, opts)
	local options = {
		remap = false,
		silent = true
	}

	if opts then
		options = vim.tbl_extend('force', options, opts)
	end
	vim.keymap.set(mode, lhs, rhs, options)
end

P = function(v)
	print(vim.inspect(v))
	return v
end

M.ascii_art = {
	tafta = { '', ' Taftadjani ', '' },
	email = { '', '@  taftadjani@gmail.com  @', '' },
	pde = { '', '  My personal development environment  ', '' },
	doom = { '', '=================     ===============     ===============   ========  ========',
		'\\\\ . . . . . . .\\\\   //. . . . . . .\\\\   //. . . . . . .\\\\  \\\\. . .\\\\// . . //',
		'||. . ._____. . .|| ||. . ._____. . .|| ||. . ._____. . .|| || . . .\\/ . . .||',
		'|| . .||   ||. . || || . .||   ||. . || || . .||   ||. . || ||. . . . . . . ||',
		'||. . ||   || . .|| ||. . ||   || . .|| ||. . ||   || . .|| || . | . . . . .||',
		'|| . .||   ||. _-|| ||-_ .||   ||. . || || . .||   ||. _-|| ||-_.|\\ . . . . ||',
		'||. . ||   ||-\'  || ||  `-||   || . .|| ||. . ||   ||-\'  || ||  `|\\_ . .|. .||',
		'|| . _||   ||    || ||    ||   ||_ . || || . _||   ||    || ||   |\\ `-_/| . ||',
		'||_-\' ||  .|/    || ||    \\|.  || `-_|| ||_-\' ||  .|/    || ||   | \\  / |-_.||',
		'||    ||_-\'      || ||      `-_||    || ||    ||_-\'      || ||   | \\  / |  `||',
		'||    `\'         || ||         `\'    || ||    `\'         || ||   | \\  / |   ||',
		'||            .===\' `===.         .===\'.`===.         .===\' /==. |  \\/  |   ||',
		'||         .==\'   \\_|-_ `===. .===\'   _|_   `===. .===\' _-|/   `==  \\/  |   ||',
		'||      .==\'    _-\'    `-_  `=\'    _-\'   `-_    `=\'  _-\'   `-_  /|  \\/  |   ||',
		'||   .==\'    _-\'          \'-__\\._-\'         \'-_./__-\'         `\' |. /|  |   ||',
		'||.==\'    _-\'                                                     `\' |  /==.||',
		'==\'    _-\'                         Taftadjani                         \\/   `==',
		'\\   _-\'                                                                `-_   /',
		'`\'\'                                                                      ``\'', '' },

	girl = { '', '⠀⠀⠀⠀⠀⠀⠀⡀⠀⠀⣀⣀⣀⡀⠀⢀⡀⠀⢀⣀⣀⣀⠀⡀⠀⠀⠀⠀⠀⠀',
		'⠀⠀⠀⠀⠀⣠⣎⣀⣀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⡄⠀⠀⠀⠀',
		'⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣆⠀⠀⠀',
		'⠀⠀⠀⢰⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⡿⠏⠿⠿⠿⠿⠿⣿⣿⣿⣿⣿⣿⡆⠀⠀',
		'⠀⠀⠀⣿⣿⣿⣿⣿⣿⡿⢿⠋⠉⠀⠀⠀⠀⠀⡀⠀⠀⠘⢿⣿⣿⣿⣿⣧⠀⠀',
		'⠀⠀⢰⣿⣿⣿⣿⠟⢁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠇⠀⠀⡈⠀⠻⣿⣿⣿⣿⠀⠀',
		'⠀⠀⣼⣿⣿⡿⠁⠀⢸⠀⠈⢳⣶⣤⣄⠀⠈⠀⠁⠀⠀⠀⢀⠀⠹⣿⣿⡟⠀⠀',
		'⠀⠀⣿⣿⣿⠀⠀⠈⣼⡇⠀⠘⠻⠟⠁⠀⠀⠀⠀⢤⣀⡀⠌⠀⠀⣿⣿⠃⠀⠀',
		'⠀⠀⣿⣿⣿⡀⠀⠀⡏⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⡿⠋⢰⢠⣿⡏⠀⠀⠀',
		'⠀⠀⣿⣿⣿⡇⠀⠀⢷⡃⠀⠀⢀⡀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣯⣾⡟⠀⠀⠀⠀',
		'⠀⠀⣿⣿⣿⡿⠀⠀⣼⣿⡄⠀⠈⠀⢑⠶⠀⠀⠀⠀⢀⣾⣿⣿⣿⡇⠀⠀⠀⠀',
		'⠀⠀⣿⣿⣿⠁⠀⠀⣿⣿⠁⠀⠀⠀⢀⣀⣠⣤⣤⣴⠟⣿⣿⣿⣿⡇⠀⠀⠀⠀',
		'⠀⠀⠙⢿⠃⠀⠀⢸⣿⣟⠀⠀⢀⣤⣾⣿⣿⣿⠟⠁⢰⣿⣿⣿⣿⠃⠀⠀⠀⠀',
		'⠀⠀⠠⠴⠀⠀⠀⠿⠿⠿⠧⠾⠿⠿⠿⠿⠿⠃⠀⠀⠾⠿⠿⠟⠁⠀    ', '' },

	default = { '', '', '', '',
		' ██████╗  █████╗ ███████╗██╗  ██╗██████╗  ██████╗  █████╗ ██████╗ ██████╗  ',
		' ██╔══██╗██╔══██╗██╔════╝██║  ██║██╔══██╗██╔═══██╗██╔══██╗██╔══██╗██╔══██╗ ',
		' ██║  ██║███████║███████╗███████║██████╔╝██║   ██║███████║██████╔╝██║  ██║ ',
		' ██║  ██║██╔══██║╚════██║██╔══██║██╔══██╗██║   ██║██╔══██║██╔══██╗██║  ██║ ',
		' ██████╔╝██║  ██║███████║██║  ██║██████╔╝╚██████╔╝██║  ██║██║  ██║██████╔╝ ',
		' ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝  ',
		'' }
}

M.icons = {
	abc                 = "  ",
	array               = "  ",
	arrowReturn         = "  ",
	bigCircle           = "  ",
	bigUnfilledCircle   = "  ",
	bomb                = "  ",
	bookMark            = "  ",
	boolean             = " 蘒",
	box                 = "  ",
	buffer              = " ﬘ ",
	bug                 = "  ",
	calculator          = "  ",
	calendar            = "  ",
	caretRight          = "",
	check               = "  ",
	checkSquare         = "  ",
	copilot             = "",
	codeium             = "",
	exit                = "  ",
	chevronRight        = "",
	circle              = "  ",
	class               = "  ",
	close               = "  ",
	code                = "  ",
	cog                 = "  ",
	color               = "  ",
	comment             = "  ",
	constant            = "  ",
	constructor         = "  ",
	container           = "  ",
	console             = " 󰞷 ",
	consoleDebug        = "  ",
	cubeTree            = "  ",
	curlies             = "  ",
	dashboard           = "  ",
	database            = " ﬘ ",
	emptyBox            = "  ",
	enum                = "  ",
	enumMember          = "  ",
	error               = "  ",
	errorOutline        = "  ",
	errorSlash          = " ﰸ ",
	event               = "  ",
	f                   = "  ",
	field               = "  ",
	file                = "  ",
	fileBg              = "  ",
	fileCopy            = "  ",
	fileCutCorner       = "  ",
	fileNoBg            = "  ",
	fileNoLines         = "  ",
	fileNoLinesBg       = "  ",
	fileRecent          = "  ",
	fire                = "  ",
	folder              = "  ",
	folderNoBg          = "  ",
	folderOpen          = "  ",
	folderOpen2         = " ﱮ ",
	folderOpenNoBg      = "  ",
	forbidden           = "  ",
	func                = "  ",
	gear                = "  ",
	gears               = "  ",
	git                 = "  ",
	gitAdd              = "  ",
	gitChange           = " 柳",
	gitRemove           = "  ",
	happyFace           = " ﲃ ",
	hexCutOut           = "  ",
	history             = "  ",
	hook                = " ﯠ ",
	info                = "  ",
	infoOutline         = "  ",
	interface           = "  ",
	key                 = "  ",
	keyword             = "  ",
	light               = "  ",
	lightbulb           = "  ",
	lightbulbOutline    = "  ",
	list                = "  ",
	lock                = "  ",
	m                   = " m ",
	method              = "  ",
	module              = "  ",
	newFile             = "  ",
	note                = "  ",
	number              = "  ",
	numbers             = "  ",
	object              = "  ",
	operator            = "  ",
	package             = "  ",
	paint               = "  ",
	paragraph           = "  ",
	pencil              = "  ",
	pie                 = "  ",
	project             = "  ",
	property            = "  ",
	questionCircle      = "  ",
	rectangleIntersect  = " 練",
	reference           = "  ",
	ribbon              = "  ",
	ribbonNoBg          = "  ",
	robot               = " ﮧ ",
	ruler               = " 塞",
	scissors            = "  ",
	scope               = "  ",
	search              = "  ",
	settings            = "  ",
	signIn              = "  ",
	snippet             = "  ",
	sort                = "  ",
	stack               = "  ",
	spell               = " 暈",
	squirrel            = "  ",
	string              = "  ",
	struct              = "  ",
	t                   = "  ",
	table               = "  ",
	tag                 = "  ",
	telescope           = "  ",
	terminal            = "  ",
	text                = "  ",
	threeDots           = "  ",
	threeDotsBoxed      = "  ",
	timer               = "  ",
	toggleSelected      = " 蘒",
	trash               = "  ",
	tree                = "  ",
	treeDiagram         = "  ",
	typeParameter       = "  ",
	unit                = "  ",
	up_hexagon          = "  ",
	value               = "  ",
	variable            = "  ",
	vim                 = "  ",
	warningCircle       = "  ",
	warningTriangle     = "  ",
	warningTriangleNoBg = "  ",
	watch               = "  ",
	wrench              = "  ",
}

return M
